services:
  telegram_bot:
    build: .
    command: >
      sh -c "
      python manage.py makemigrations &&
      python manage.py migrate &&
      python main.py"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: ${DATABASE_URL}  # Передаём переменную окружения с настройками базы
    depends_on: []
